sprite $aks [69x61/8z] {
xPU7RiGm34DZYTJ_VtAH6YBWSL7t3B49-tL8vFcEHUQWjTLlXjNU7cCy2yWBudRRAqvqaJmXua1-jzsk8IJ2tHFIEUpttN7Q5QSV727mWtJtX4X_1793RaYG
54GHP91ua9qwnTvJpqsuhpJqYTpcieiY6Azus_BhQgjL4ipHzlQZlfqDPeDElLhrRNhCcSHk936Dn1afpLhBWLoEvF2qrxx5lczFXvpMr0vokxs8tVR-BGZ_
mV_a_fy4CK7Sb9qvKWW2WYXI6LP4o5kALMs9qLReJV6MfvOiR5Wh6bG_mErOROR8drguxPry1sF_9u2hlQhVNpwbLEIoBsJz8D6dhGkQwc0_X01zUVDq7-w9
XTQnu5Z05mZQSTep13yJSaDkYByMalaJ11b0FOFA13QCRoblsmTP-GnLQyDjzwLRv5e6jbtdCKp-9-W9
}

