sprite $azurecdn [69x41/16z] {
hT5NaiCm38DXi46-_uMtBuVf4SPV9g-_9G7lyCWYgzAX2Wwf9oR7jc9J3sEyfzI6Nc7JAy67GhxC90sZ3Mt1GTdPYqsyZtL2lu-JMYIo5OUTaNsxGQO_Z1Gt
b66mZd3FPSL_9ITn93Qzujo7Qyb9tBgujdyqMDQm58bkw94w8qA47cc0JzGYb_ACYCkHQGc8Ao540d-uT7s0e-a7YKEk5FxvCQsDFu4MEQpZROM7dCTRLk0P
hpSIYPVCFHvpDvph4m
}

