sprite $azuread [71x65/16z] {
lTO9hkDW20FWiZcv_uLd8oeZgzOJtJZ09ml_eRtzE75xnrZKEvGCvEjCPW3ngXB_6FXhYcSpy5ULPc2lh7UOUaKPvlcwSfWNd206yOeo3FovafXfPwym0zkM
z9YflSBCtWd983UAPX2RzMe6iL4q0z-iLpEmXQAP0ylrzh1o7BLLc3bwShNU7bBQMIj9I4yirjl3I8-lb8Yu41xJwsN2_qoWXnbeXObXM5ArEnF444KEAT64
O8WwanKRGZ9CdUSPf111Z1gktGGX67ryTeo-pBPc-dwPNK1SoPPCrvJ0LEqKI35y0hq0r3oOw6YAqL7GZkKrVXDGgDNw_IrcX_a_a2c6MwvBkOvO33I113DH
0dS5JX_bh9ePRhcZq3tLWPZ9YT9ApVMIWPWfeoW8URIcUsPYMeOwEAO21RKie-X0pN0Kkdqyzd3LGIst0XS8hRe3NOo9bXU10ibHcXKZke_sgn6EeeS3yMed
oZAG3t8ClGfarF9hV_OFUd3xG6rie_3NKQtGWri7gatB-Z6MU73BLPU8iWnKBqQX7zLlp6y
}

