sprite $azurelb [73x73/16z] {
lTQ9Ykim341HsThw_pyyYsC6t-IL6I5ujsnjauEoHtxD8roQRGTImu7KS20r74WD1rBFwKknCpkaZgDgiMiwa1eEf8RJaE0q93WjAIBNPpcGhj__xEJLSY3b
LTISZEzSLnxVPKMAPBfA5YM748kIGuX5oI74ekGGOb5o2B4eEOHOL1oVOyYO-GU93hcOifj-Co0z7TCyKZao36hRU-kSq1Gquu2KqjDHEfHEY18TrnCoMQb7
kChAJuWI7K3otV2uMkCDG7Tfm57VsVNVJsFjyDYPGgB3vbuHpzcf2D9sGc_jWJZIqBUIqI4qusYDg6yaazpPhv1kY4LUYK4gJ4J7HE8csKw-U-mZsy7PUvkI
vUv-r0pdjZySI0l2dnn8710SIWUKupopVJpFR3gKJiXbDTzSQt0UKXnGcjooF20wJybnNtldPC2Xn9wI9w93YP6oujt_6SPfF8y0DPwGW7hFR49qAfBAQdJV
QmR-eLEHflmqMkz-SkHqIfB9qOHJarIEHi7P_HkQS6eI9oevkyZNzmVh-F5RGNgjz1ZejGefbckruuHqE7Lfxdck4LDGHNgvpg6USCeIWjEGuBIab4O9foNH
wKiXxH9Efu3JQGxvdtq2
}

