sprite $azurelogicapp [68x53/16z] {
xTO7ZiCm34HHajACs_tlkqwTc4QAX0Hj_L7Jdfj4nCu5G5XBbQXXoa6oqIXSWzzVWvq6aLw6RGeEZo4PNdcgN5_oL5XgdBU5fPodP12McvyO2iaejZSclHXa
g2B3dnc3Nk2fuV_LE8pn2yPSurePEurKZy5aU8TXSOhBiiGfjqP3OJLC_T88haM7eH-wnj4Jm-r9jz6ED4rZtBIipUDZWyZWAHZJtHYMTy4IiXlgOujHUCfq
BJAcyLcp3DErw9xAiEV9q3tL8seqz4EjiLP3Q-pxHk6zOligxlbJ0p9W-wZY1yPX78P_P4Iz5rrhlQraMB-H_-EsXsJGhRNWgSrqhcrAf65EjjyIf2NWw3JW
fgAYsK1r-rv_
}

