sprite $azureappservices [65x65/16z] {
jTQ95jie38LXeLrv_mSUa1KRWhFCJFjrN-vVatD22cyqOdMFnoFSZH5-Lcj_hCAumQyGQGf4_t8mWb-mKyTzkSYACtmp_ccbJgEiZVYSQ9OFJKEalM7mdjIf
ZJg9MsxQu0qzvftS7S9KX3fc-h2Fv3Hud5oPBlS5otrHwjZNzUU2rBxaH3nyNzyNM9Pz7K9TwHRBIm57O7sngSDzgEQHba9ZaPYvknAsrjQnnsGzW8XFypJs
Lq7CKvmKJYGYRElUYDfPOFMq5X2UJ8HPbhqIFGjOywtWK3X6W7tQCz5P8FEq5wG2_k31rdqL497CtXGWqUEXtEbpRtHYmYnqTmMg1tWO3yROa6JQg-d7Wa67
UTFCRx5MSxQk2heceZpV127hbOdKYTbLg5-z5lXu5qPexfU2M15CN87j334222z8xQJqld2y127mgatxB5mlfPbTWGPvVyDEQtrWVBwKt4QUdm42xG637TPw
AQ0qA1f9yZKak97xYn1sjRyAcW7y72YZ01UiDvJtGFife5JxvH4oW71ZsvinpFXw0ceDsYkz2RGP7O5uH4ZReVqKi7o2Q3lMFI1jnaT0Hu1k7i3sWAu1ou2C
G61x8NS1OxmGitWeK0OKLsHRm0R24mzAq38GZ0lMhM1BWOHJ0wW0JN4YsWfMX7FkRfa001y1ew7MpCyBQT-RkrjT22OPu14G6iGxPgw2cYtp_L8p0ZZEGCby
a6U1SwWcediWKeFE7dK2zeDae19rM-BT0uJM1qkTGCCFUXK8IjltvrKQ3wR1mwz29TPRqjU0BV-v9Ouu2rR7Q72XrtsSUM7gD0FhGy2alUxz-YFcFC5IC676
l2VgsnP0E14JSMNd1BOPYzgq5vZa2RQ2yneuI84PCbdi1MqJvCNsQHfbAM2x4Cy8Nc3S5HGll80Dnrr2yCbKHRRzLjWITOMmT-SVCDoYM7bHjPeNXZUQnNqZ
5WJlINoby15wVEG8tv35UmA_G8rRnl0p4l_lwz98B4zjmjZWx_a7
}

