sprite $azurecontainerregistry [69x62/16z] {
xTG7RkGm38LXKXBVesVt_kSDJ0Wk6bjo2Nh-z38VI3SvJrCn0mcphFAeRDncIMwNm3PakPVnADnPIi7ZaAuRF2_Td-Ev0dPJkL1XFyYun57vxJBHZK6UZvAC
uz01D8FNqbF2M7k-J-QDolY66sTo57YlrqPa-VOkK2s3dJAz-yPSBw7szqdMwBrOugOiAY8PlgkiWtWlg4W6w1wFM2ribF4WyyHgc94vIx6MhzMDj6F49a15
vjgrgCDjH180iq0if7Oj2yIw260e5J6uVwyLew2Fs1w1mUUOwrgnil0cOkva7IVMcX5_W9XnESeHdo9W7EL0y1WnB4VPNY6CUII_G-9RaQi8UeYDaENUYN6E
4HqX2AH67Y9YNIGC_--R27mXqa4g4VsRV9ljaTn5fW22MQHcC-af8lpCh_pGtQVF8dqs45WHATDXzV4CmET22gfPRddGdY2QWHMfqjH8KbCU8cLviZN5UfMQ
LEHycE_BdcoaoQqIjGmV8FMARIUJVPfoMUlUW8PbCkbrwIx-5OIN4R-2_24MtvB-1Y4zkezO8FGbeYILVchO8VGrMavohVPH4C6oofsqR16YP9K79Gk45ki_
Be_NVzyF
}

