sprite $azuresearch [73x53/16z] {
jTC7ZkGm34JHpoZT_yARWxPWUMmDzW56Cb5WiTtSiyZgRwhIEERP_uZ3cEfMoNlPucmhwvtY3UyRTfoZxB3NURiMfqdP7uhZ0oaUAEsHRc0UwujylL3PzRTk
BnSALbOFh-Hv-SMOHxZy4CMMPIldH_eF5SjETzrYyr_FFyhN4pf2scknN9GjvUBvdoA1o5KjetcVenUgp5K0UNFj7Zs6FWr42i1_prJemMjSAI2LWwqppYB7
fRmA2a2dVhDnhNP1FLOjnPvNG-PQ5r9z4LI03z5w8MLWAO2ulERQM0MWpQvFuT9CD62b2_bcqiUU0RuarRQ1QsDzk-vKQUpc2_8svmVFgieqbXm5TPkZV3-T
7-GOY_twINoGCphu9Nfi9NwVq-ERpcyaHTIFxsZAi-J8k-rJCAPQSkPJ2NMKem9yYZZ8cGR8_3Z96G2wqa7EB02zKahEqsPWKvFmdkyNWfYVPFoIyrC29EbC
iV1FvQnip3E9YfEeDYv4pNT6iEDP_J2aq_WVlW8
}

