sprite $azuregw [53x70/16z] {
xTK7RiCm38LXJYdtFt7bKJqGDkce0wlzksjyUTcc7uhLPofl4O4utVEA-JL-QsPfJ3r9IxEin7rPiPV9BVA7-Ea6cV98pHrPFMICXwsSqkGYhPfAZsa-9JX4
A6wvfaSuVoYCOic1yW8v6ue79Rb9T9Cz82kVo7gFj7mcs-CLGFntqJ_ItroI4PRa9fre_tCOqzLi85irnWCbZ3DZGfOe9hebG60meri310K31GBanrSqLsL0
FZC5ufqnIo01WQ5XM94b20e894LW4Lc1e2Ao4XdOZa0qHo9G0maC5OZ4mIOPvXPz_WKL3U5l8BwS8bJLOCuqGMIEyJrwGbXghILBwMrgUvxV9YGmPrFLZzDE
UdTc7Z_ECIsG7QQFd8YyZzhJC-AS2UWSAz5EW0vM8H0WZ2MemG0TUKJDtOylaAugnxCyZW7DEX8wueuy8X2eQL03WeaA1ZaGI50mg4q44xBnzRfy-8dwQwMs
eyIaxGyXorfCz04
}

