sprite $azuresql [69x69/16z] {
xTM7OkCW381XRK1-__Sz379ApoJ6kJs-xg6_ORI57m1dtfm_krKW8jw9y8wgnT0nppB5V8Gk4ool79rN3P9B79MrnlqADYmhwCT7nkMecbbgp4nLn-KygV1m
DcefbxDaBKJO2Pni64XIUIeROR1Pn0a_EfOdWQIC3xRD8jl6E6AMOrFCL9XnmBvD8vKBBk6yRVD8PumNIDtzHQGhIay3ahnQYFWkAVFG8cAnuc4nClU38_yZ
_oFbVgG80G1f7ys2xQFi3JFhGaGXj365WCbtzJs-ZYGO8z83i4lhaNqfrfPH8nOFeSZ-JbcDE5H-e6DLplKzlHKftkrB4szoVPVMbnChE7OrUSSzlXR9iADy
3EOXaXOYNKBOIGpwpKY8S-KOlBsSK1WgQtjYmq7vdKZVKlKS8t5Gl1p9BP9RnAczgVB-NbgEW9QjNtVhBM2r_aleFK9vLoA2E8jK3CUCmWEM7WdS8s8cqyXm
Kzpm6Ce-YrXrZYIXMk3aeHZJn-rtFgZl4RAALlwonGvzbYove5gb2C2A5n7dKoNPIAp2YqZfAnfaEv6BY6Ukp0TsSlzVnlcXwFiHPLPh-8r8iiVfqflBoMdu
wL5HnZkHR0627Mv4qjSH_LMHKY93dvQZTFTqh1aV24ALtxadX40wN3Rw7ZSMvFvb6s6lK5cEP3jH2EAB4JiJU91o7IaAg6O4f36EOWeZbFGgaAGldg32tfYh
vLnEyzbwOA33bPj36Y3Cq73vtuVugVu5
}

