sprite $azuredevops [65x65/16z] {
xT07aeCm38LXTIdtF_0MeXc71OEywUNBzCpxZGrzJ70UCJatOCRd1apndC14pWWaEYjmnZt46ZaZyDzx85ipV0yIMy7LezLwg7XqdxPpY5dKgaStV1nQgXwT
b8ciQG7rFRzRX5_c9p8WnMqlG1jRQTjk0AsqxGUiloq5jBEj1hYphGRGKsw70-O9gdm6_4K2dy0d4AaUY1E_WKyWxlW5EMCV34HgCx9p0XFKCm99Y8bmFB3y
mqrLc0bnD42nu6ugmaHO2O349hTZhHy0Yt4mStQ0uZ3uOvYJmv10-Cj6zWuhehvNM4E72OdlxGMQvJCW06fiNPyWhJy3mI-oxlKH-c8A95vj66oX32GKhrs_
aGoanNCmxB5vOFuSWR1lzOrvkef31IAiGGc5I_i6
}

