sprite $azuremonitor [71x58/16z] {
pPO7ikem34MlUjx-5_oBvN44OvFuzKDlPwuA4Bo6H5HDLHZlXjKB9dWFtL7P5ubFOMnXla1n7p9VOlSjddpGO_unpzgoFp3nIsYZCHyhI_q6Z2iyha-NSLZZ
5dY1MDn5i80qDh3bc6C7nnIBJHRZsOLc6nVRkFB7ioJwWRwivixn4QYMz74FnmUXZJ3kRlznz_acnX5nSN7JYldZwmf0ZWjEXuYSfkCa2B0BYJQO20aHQoEE
WG6fNH0jYH0UePQg103YbMKgwQ8QI71bOIJ4t4f2Xwl746lB6INxGG3_ewj8Ja_0NrfA1Qb9KYIgsj-xdjImfAHeggT_VBatNYrLqy5_LDKp3TObqQM6Ubc-
MXmxPoGp3HBEE8fvLT5BSWOmqG2Wff8MXm34EepwyAItMfZGuqGBDXyJ07OV7aP2mv8ULJro5ZuR4-VnKlSmJgXPr5ounq4IRq_qCCk38bB_X_OuWeIEHyin
EZFrSAQqqHtCFPuxytHinHxE8CddTFHQbOOdgiPgJTaSzCNmXWedMHLZO4MJvSfZc3YwnnZWef6g0SUJnXuFxuyaAo3kD8q04r7li5Z2DKq0HLDxN16Fuor6
qogQOJ2Plc86fMRcqSNRDpG00NiQndrueO6godrK5OkOUn0MiDo7yUlu2m
}

