sprite $azureinsight [45x64/16z] {
ZTC53iCm58DXFqxlV-1HN8Rbdt3w5Bc4G-9HDKrLuOB7DDgqgONUqvfErJMNd2vBELkRxcesPjb1vvrhlrziRLp3jOss1ybqmO-KWTM0RSaH3xPwxPFj3mwt
QDrIkfdJzwELj2cVuqAp_nFKihd50gW2ID8gWQWf9BiE0BG1-KmeG6Rhm9Sfj7hh2eFpoLQtime8iSA9fJz61xBRaX_E08XjcMm_t3OOqFmKGFRLZaRia4PS
EwpGx3enpOc8XQl0l2SGCnD89FMAczpa-OjupkqirI9P1Mh_KhX8_ShyoDnrY_CIv_Z93jlZU3XP8JlRGhMeLMsF3z_9YlECu_2XF9ui-DHssEm61xxf5kUA
pVnqC91RxCHrm0wsmrxCVOinPwlEyBRWMArYAHTS4OqwOiM6JMtMbRd5zQELsAPRJFsrJB0hbXtLg3DdR3ZKLaozsCGn8rwg9S6flDE1SpBDBRfxmKLrq2nn
bP8UkEAokjA9wu9mn_q62zdE2swQpZNSbMSSk2tgKE0XiLs2KUoUFeBvHVt3YmltVpFyopvkQ7DdxFzckeY1pOkB-BjPPzV3S-P3puJ9eANMHplU6m
}

