sprite $azuredatafactory [69x69/16z] {
xPC7RiH030DNqdRz_xzn4o0dki1CBvxh14ZCkIGF7QItGGOJ6VW2isI7yBO6JKWE06PMYnmZwynLZ_m8kUX2pgIKKXUM3_0FoR5IMn-Etkh-RoXV656cbMLa
d5X6Q4NqoeXMEf35PwLa4SkgNXfPg4mXNEUyFBBGYz09ANqkA38oLqPlhTRMsfW6PA8p03O9-6wJs-GsuHS1RjA203LfGO2QD0q2qAHf400cLWa2mCGgvm0p
iKeG02PMyG5gOXKVe2PMyG5cuYik04rynGBKn5SiG4rynGBKv5on03CvLop0J29GavZRv3OPVMVOnhCvD__OXDD1dmiwAUsmRlHqa5ypINv4TIH3DrewaC0a
7fd0o1UOt2QITkYuslXS6fHsoZ-wYs-JyNwJdcIyrsHm-X2U
}

