sprite $azurevm [70x65/16z] {
xT05Zi0m44FHs9v0xt_WvGsKEwrWuKiLLa-UCDwF8QRxnP2Uw5Se_qfyG8c2ubt5y9uTAJcbjFaPyHbjzx-Gjuj2Ip5ljwqaOKpfkc9OPbSLOIrTL2Wk39fT
LKZDXvX7eJGQFeKKsp4-fJhDS2ka8FChhHDAMQyI0AdgbFME501jZbF1U-qibm9q2YMNWb4XTLr1ZIrTL19N5EMJIYjofYYMSbffsQ1OAIwbP5N5Sl4exNb8
AfNTmdIGWOpJGOVAL5WcXxBTl_Als0E8XH2m5NCViLNOZQMFmT5pIkxpAXeKFAB8gwG-hsA3Oaub3ahq8OXZS2aMn-IQOlCSOsZBU7M8R2rTc4FjTNAGZZft
p54ue_2efZpSAm
}

