sprite $azurekv [69x69/16z] {
jTJh5jqe28RXJmJ1kVyB7fLiLh3PiSVtpqnFJm6pYkzHbQRMkscJIlZr2cl_BzML2tuXQW6OYgZrqO8Q_UmGUltLlPlmIYRZaXQSAys5cNAaPX-c7Ha9mfZu
5jNXc3k2jwXVX19GE5K0YddeR6X169MeXeBIpEnLgKuO0M4KxF-lhbGy9cu8hZzNHuGLtHIm3yDuYDqWDweNGzQRGbyLMeQLC38o2cMjP0ztANqQYcGaP1GA
_Bu5EKj6LDBFx8eXfMkNpPZ58BkoDchxKNlV38zAeUfbnKRfeNjwbzVo6rd-GZh7v2Ub0l6zS1h4TkEig8rmrT8ovz924fz8l2xLdrBeziuEYW-o8VnKzJxx
51lvAEONsKuY3ss8NqKNDmUf-9b9wYU2HvzzEBwpEEonWjieV6sZ-FGsYSGeyFoqUct3IAESRbBmgSvHW3gHWeZEDo54PIAKJtB-LBBXHwaGV-2id8rysHPt
ZUXifCiAT6pJyAoS3OYQDLXwdAoS3V105Ds_rxEIZVp6pmZeO6J4rpahsSZhhCCAZaesziEsWIYUbRE1DX213CHmLWYFwK0OV4RSU4FgHChl8cKYTVrJOFLt
rwaJAO2zNPRbNMdhXU6NFIDPoIS1Q2Brzn3oRKOs43qZzBBDjG-T4FhsDkp_En4z8ULfaDW6Q7cKZ72z-d8HWLVwGEo0F2Ww4NoIYV098UJOBnAjKUY05AGe
3mBmKbuHBW_BvF5j8efS3OIPwUbb6g9GseOm3yJR1v5fA7AbX_ACrDtmJoHN9-9sHg9zbwTFYvTYz1Mfjwzz8dcshF1f4fv467laYX8yudktpoFjibTiATOA
LZyQfRcX1Tzh_MB8bMpGHLZ3QzLSCLtEpI3HYz2AKzm_p4ZS4FKiBd-gj6wHJkCcc1JyNDHkYeXQb8XZ9BQdGlZbYAMrzPxQH9ZmZ_iV
}

