sprite $checkmk [79x85/16z] {
xPX7jkGW4C0C1kd-9vx8nlsfAHmcjzOykNXotluotfJofArhVqpOHB4z8jj5076_BQiYCB3UAy3HXfGR1K0EDgMNwmNuWDYl5402v6paYX8Z-ya22R8S6LTq
ziMS4vmVuM9E59nCsB8BQcQJMf4ZwOLNWQckVPkRW1had27sCXRqA56P5P0NV3qXwbptyS9h12lRwpfnrgczs6PCRi6bovGMdciog44mKJ7M-QeRyyStUs5H
Xy1nd_cEUx3Pv0AF6lVvT3ecJzZ1NEVecLCwXhehDxAAgOwoBLF8TTi9-c_MrUF5M6_fIXlB1jrMhkiglEY0Ub5NElXHPozNT3i24nsqqxgACDE9I5tKoKWm
c4u7jB8-tGwHxlYMmeAkT37HZIIfJXe0gKwmvJe5DDE9eA4k8D8DVelkhNlhthf6I0jryRfsUphRodJ7ryQIRZRtiM-3NTEZ3WhW3xzhAiGCsK4OOg-rIuGb
-YQJEOR3QzqYTkSkmR1e_Zqh2xZqnTr19K54rd_jPBZ-5bt9SJ_xKyOuSb0WfYawrGK54lhCv_YQlq2vLo1lOlw9jIuKafnhaGKmpRdU18ESbvkKxJbAtVuk
tdm6
}

