sprite $cloudflare [86x40/16z] {
xTK7JWL130DGE-t-DwR3aYMKaOV-tm6iD2duYophNXesOTPpIMmGTPPGiIO6YTVCrT1PoErl7aAzHTx-JEzVdm4zmbgfUh5MzzBgFLHkIRykgnNYBSqIT3VA
_NU6kEFKIpq0yOZRKWEC9xOhbV0u-9xKF0RmPYnzyQoYCMNzHoWy6fonrYJkHEDQeKayi3UAjJfBwuYt-J1PzTkHGx5PQnpp07fgBJlQxePLhPv0lDHANJU7
1jLKYy-eDVQd1lW9gGHzG7oUYsi
}

