sprite $consul [78x73/16z] {
xPY7RhGm48JNtVkPzt_Tlq30AGk77HIrVDAfmZ2UmUMGZLzyp5N_KL9myYr21T0D0BAVbGBq2r0cB2RG4r0_gMK30_uyw0keSfE2TZwse1tk3LVH7QX1EYxH
1Sdo6eUHjfdehSXU9XDMFGR4hblBA6vWc4IvX22lESISV1zz0tc0rDiQm2Kd5imugs2sFpNCYAeQdGHc2j2LSZ9EiWnHC6yApDNPLBMTMVCoIjLwEWla4OfH
mJnJgLrFTv8yGcB6cZR2CI6aKoy7wb99tau7VxnqdsChjjQo4Or9jOcqtc1N8uX1MDh6eb_ICTHw2SvqrdQMzBKvojUHXlCIMkiiiXBh5abc3xysa3jgI-ii
QnIWDBUwYxqR8r0xjKxjsvfqxgl53sg8I3Qk_LblTcxnBJTjHlsJdIQjibBtaqffJKLctxU-xEBtA94xSo7rkM0DICzcbcQnyCkoj7-_93TdbbnlfJxN4kmr
aRJbz-7cFBFqPa0tCu1ygI7A6C7zmBuWi-UswoEgF0Epve9HjwJ9v431CZTJQyA-AK-PqvNwq44rSt962FG7tQUXSEvQ6PChciM4BlVWAum-TLIwDyLga1lK
Gwx8EGwGCJdYvJKC_gc7PFbIRFCs4Tq1ZUv3JON-i21tSA07qBIK56Cg5T0EMMGal0x0tFULRi_6ZdJ-SmqK6SKhJFgoYGfe1o0xcSV5mexc80U__0K
}

