sprite $storage [51x51/16z] {
xTM5iWCX38LXGa92aZF3-p_jbNgxrklwZrNsMmV6C7z9NSReU16958EKbqJP5ULbUVmeKbbqb_0TX9e5BWiJMY6a0S1DcVbuD7zcia38W6XrUfeMI9qZDM2r
p2UEg1DICxai9vdrbdZMibRDe6j2iBAUGAu9esqGWjwIla7Qb6oScM1A0buN0NN4b71BkCm2CS1eXXJIHBeoNUwUjUSpA6MExFON012-R_SbTo_c0jb5ekRk
kOEc-yrNoRHt9VBofwyRX7yB-IToIoYIri1kWsjI6CahWWCocM0vLoVObALfN2U78h44Z1OMYnO0l6lZNQBc2Q0BhIr9OewBeYlVjLRo8VhnY_WseHUIhcal
CTIWGnClgeynYkbB6kCH
}

