sprite $firewall [65x51/16z] {
xPT7SWKW28QnY_bdkFzfaxpUM8clywqTwKsaz7cAY7HOw5AGQPwCqWU5D4kaqJjJnInClEI36nYL5814Lopvm3zuZJpOfJ9GqYq5I0e3RPlAkmzq2tSaW7Qe
NZfyu1zatW0ClcK0hF2pUzmMvK6gLmnmLG1QlIIlg0N_m1u5UnxOCz5U2_w1lIlxWk4Vl4GUc7TbyxPklXVC5yiV
}

