sprite $grafana [68x74/16z] {
lPC9ZYCn24N1h7F_0_SMPp24M5PRwgSr3lNuK6Nu6zWTBZ4tTuGRrEsBAmcx_N0pZjjq-Cqo9ZukOjm64RUGo99a49qlTC6_KFmnV_4F3XZkKv4z-ZXsEJ5O
p_FSkwV47mW2H8QMtc7nb7io73lGRKzuV-Fm7oBWkIC4EjOwcPhk6dflC8GAshJuYSCTUgoNU6CWU0UwDptCZqBaUcTO8JzNn5toxJ1-S1lCtBBZK96ZUzK6
QPtRSTu7SJZYfH9zfnXYNoXXxPiJQ-Hu_JJZVKdfMvDDSFljkAxF-9k5j3FsA_VKSDWJwXGPZGKm1DB7Q1IfoBHTHxCaUIJcroIftFH14fELas6pxZa3jGvA
XxCwqAS47lZQuEd0V6W26Gb9Th3fn228tokfMSuyAVFPWA1KvszPtplW5KgLIT7F0eaKXCf9iCYZBYErL0iGl7EC4fcqWAqZKzffXLEf73XONyWl03foP9LA
MeYqmyodDewn1fdA36hkjWyYhOIrTDDT413vFmwMKVQI_66Bg12nQdRaIgeMxgv77B84PS104JAO3ZGvWj5DqvCZR_w4jmn9m2yaA7i7oS8uL9oFsW-2q209
WiAkGo2y8C9B9sHP_eBTrZaX8anZ36AHzHWt3k8JX623y0a4EmuLruu1rmw4UmVyjGEGhXmnDWuYEjXeCEBj5JVz434s40s4Xkb8zcDo4eOha4Dn0NPZVW8
}

