sprite $hypervisor [51x66/16z] {
pTU5ZkCm58NXugNpItt_frsm5LYoCnJjcMbh-iBuUZtZBNc-Ng-WydYAU3cForlom8FBsqASIMwbcaQs9t8x43qsSfCTITf6xdKYSNUpjUHBjHN-GG9YAm1u
hr3_8WPglm9h9CsiXYIXKx9vrBm6923N1OG2CuSQ41DQlo55MA8SaGHlWpifqaIEI1yTq8iPo236f929MZGas9W49CH2XD24c03PGXB82Uc3zgk5puYtGVlz
QJDYcRaKt2mpp3nZG8OvdrprPd8fFq9qtv6hnpnvF-S2UpwvMixZjpt9j7b2jm_jodlz_oHAQ3daF8KgXiH5JpLEJuw8GE6XFamep0NnRnBGImLk3j4h-MzI
iDeq0-LizK6sbCei0PGn9cLx7AAfutCnCuyKrD5rYSnM4JgmnGHk2RvCwEX-QHLFg06nl-vz-UGO0wLRJnPKddlmdqykEaOUEtAlF13_zMfvkqzpxZNvxQy9
zewNaNUyydm7
}

