sprite $jaeger [81x90/16z] {
xTY7RhKu443XC-K6_bmitlzjr_PYZOY3Y2ssxr5KRliq7gCMVjB_YV9igazx-YXdfiA3kPaUD8za5KJHHq7DFRP2AvnDW6jEEANOqRYtHWHeBM4iMS_f6LIL
sV4Y9q2PylgG8XBDUH6WXfSUyHRsDtXjmkjZttVCVT_VDklrOFRAtnFUGlMMb_lx2H1e0wxkxOis2G8Y0dxKG6S6f79gAbz1eZvtfmUNgbLEJ-0T5u_hqgmN
9QcQcOg0bJo7tfxMQs3GiWDJbHod76x1b5PtL2ChDMrPs96r760HSBy7FRc3Mgjn0By_rt1SXUVi1hJaHMoWQhQQLcBTFrdgBNdjViG26deav-U8Ck371uXx
wnvqCwEb1nKU4DhDeHqA9n18x_cNkAeec2ar-zuJx-AgfJttU-vyslO-U9_TYCj15dDf83lxXNTxqMQKKWPUb69gSQYDW2w1b3vtNkwLTgSr0hQicPn_sOjs
vqNdzow_U0DsFGE-RdObWo3z9CAfCP3e_BEKKW_ABGWNuZlb-cNCWsaEvDGhJbP5fi5-nCWdm7xzVk7TtWgbwstXqS287TWt3wRQ91ZYHdZ1Zu9qwm_Gp80v
CDPly2jh6rXf4enegGGu96htHOiWmBaHgPu0fgee378zQDRDttkQ-vaORmNMXQhbz2UWKVBwnmruANeN0Lw8SMTz-gteZb-7NO-eYWy7boEgAZEYNeAc-YXe
PlEWScv9gCs9XjOVRX2b5E3KY5g88D406GTDmuiEK2T0O7EYiuZwKCfbb_zpauYnb7zqgRRnJ5wmHyLjsy9xA9dtrgt6kNTCE76w0hufwTOgtZQXLKlYZLRM
dEtDZrksd76LP-izD5ZAVNwxJuYZ3e6nkic20rwVXLm_UAejRP3IByRwlzy
}

