sprite $octopusteamcity [126x67/16z] {
xTW9OkCW38NXXx2aHzRxdtPM71iRPQ6PVRuB_4K1jGqsPFf2i9L44dwmYJU-ZgcPgfhY1yfp-2lIKObfPO8VnJZpjczwOpyyxlIAr1fVu8TGlzLNID669Vm0
kJdwWgOR-06y7_TTt7v4tEVuXiRr7tzqjI-6wvBLMKgXJP8GigNUiDd0vvucOxaXBICGnBKZuJdAia46_IL-MZdsF3T-OUcWeYCjzUjpSD_4qkVOapVNZIN2
zAFhoXBpiExZzNZiZ_FDsI-7ghYxVQyTNOsdfPvUkd0jmqPpzYFMlhOCLPdhT4IyFDAjUrJ78j_gKJ-NXoQqSettwZKkgQsxKz5Hdf3GAlEQkrRbQ_WRmHU7
wnUEj4p-As97IYW-l99iwdwhr_5_TRekzI1VdeADxTbjRbgTTuiUvCVg6jK5mALNhz18vIa96q6z3Zwk2zQqF2LZmpbMP_pOOnEsWde6SBnJz-7w_l3Mtldv
zT-hwq0zOolrwzVLae5qwZvGJzXnTki5N_5ocW38U-hOatxzch7oe3uDr-7RUgNRU5p7uAK3FAZNbLEt_Jlg2JlMr0DDVVJ9ANOc7wmRrjBWUnkjPpHyPF3q
mJg15pSzW_X8NO4NH-_OK1-jTmxoSfsZTQQFryq7wynulKwqE5YduEDryQ4w7Ht25r-SjVNJf2lJgL-d9_HOUV7IiwqVqJZqwb4RYK-kshYULlfrGS3BCwQe
_fpXU6K_ecxbMPxUNlVo0dblNLXUadSlpY_tdEitQOSJzhHqk0XNlMbUEBfi7V65XTnnHxAbcBX-sR8-hDHwIYnbF_gO8D8aN32rEzNMEqxs2yVyeGbtbSe4
WBSNAw_hqE35nzYsem-TtsjfkzAur9TH26xyBiDBfcNkJPtjzSI20-r8gMHJBsZo6JV2k3rOrzq6n2nlwj1-Fc6qxhi_D8c5g68jx_AixQ4wWvydHBRnZ37x
lr-iUMG1SN9E3xU1gT3G8fit5adPt4q57o62ZKmMnoyZXMZzzna
}

