sprite $octopus [87x84/16z] {
xPW55kGm34CTjfPy_zCkOnhITBpy7mvKROnwjR-H_qZCLV4HhJdOKyYAZXRj9j8m9DyIhHXmLpXZXTf3Y693D9w0FNmW12SK-bdFIEIpdXAC0EVOEHNdA1lO
PuTNGM5dH714Em8iN74zjyWQM9eT09wpwlA8GWPF8ZgCeBY45jL7jlsNTOjjzf5DFhB1fnriJtB9c0beXDXa18HF_FMxp6UVDmVtmRXHXxtBTuIT4dra3GJw
HydYLyic7zjSuH5SyHarrMNM1B2e78N0GrVn249OV8R4laEv7uY06xmGOZao2FyIfIdcA3vIwTbzFSltRQCH7zbMG0xNjhySk7ndbr83T5EjPQ3H3RQkpPEP
XVM0hNrDfC6z-szaCxVBPToqmGpIFiqgYtobO9yOrasyo9fGRZIENSl88J5sj8s7_-XR8SRkf7LUZ6ucj6nlt7Iym2ejs-nxqbZMGZboZc4MhoxlBBDmTR5X
cTLCuKpj-FBv_bHx30NAmaSbUn1PdKFjwKIWsI_aF-y
}

