sprite $office365 [111x72/16z] {
xTG5plCy403XYI7UkV-1VoZuXPHK9VlXb1jujBKQVcH_yzf8isOSsAAQ1dgxE7Aqf05NJVH24xsccPvFozLqSLOFNJXd-uY-KqiQRfOutFi35jykCeTJ8vUp
vt8cSxxn5yXOlk4-fM6lZ-UEvMekFAwwRy-mD4urYriraTD4BZoimYRDv3oqN4qNFjVLnFaylYVQ08xnoeDj1tXthPlS6jhtu-Pb-iks-Pu5MO1Rfnkg5R3V
k2ZUqWJKhroXAeIkQCCRDHKLDEn4X6zogDevFohUYSMO-swxmyMtZLFjN0eMxO0Mm4kiKXvpw_Ff69vYcTEns52j9r4r0fG0mWx4BSuNkBdfC_Tf6ywJCHTt
OVYryIBNF4MnRRXJdWFfAklj7_GrRdxZ3SvF1JBqREgBN7pZf5xL_eaRgWoT5LoO3gznnUzSm0BuXGkMplaPTRvIuVBy0XTbtN0wbkActa9jBIwVXggjX5gN
rLlSS5DbvgxTFIFdUXAdiRXtRN8f0T1oEKngS2hCYKkc55mgPiJCX1OolO1C3p8zIFI2RJLfj5buH8ExTVUkCZjunbZvm_eN
}

