sprite $powermta [58x48/16z] {
xT975W8n30DGHLZp_7J_0xEXCpK9dRztDrgbLs7FIAw3daAhb9vp3haAqSFlVSB_4_wVi4Ebuf5F88fc4K1wP4w1pXaMCDZ7Jz0PGHFJB8HjZ5YCf6tpNfcC
j9s09O_JbqHAYXMH4xuladaXjaGMNU2JvkIDzNFw1jjhHewBnJanvUCY1qsRZvobFG
}

