sprite $prometheus [87x88/16z] {
rPa7SYmX34HHedN_4tzlA2-_ZAOPnh4h6_FGjiAazgVrzoLg7lrDuQRoEKZl0F9T0BhhDQRwI1pP5yY6F11i2-f88lWdGBtXAbW_4gp9D6AzzFjxQtBD2UcJ
tLfXCo5B1aottbQoadAgvKnnM-ebrwYjrRunaV5XtRUegMq8roq9bpg04UlFeb3Y0yrMrqU4ZsGB7aVOgRn9pieLBsoBHr5epYG5ji-mZz26d-DbOz1qZTY6
5rQGAMK5Evq3Oxt6dVxkGbN1nNn05O0DSMZsiMAu3LxMgs3e-kS9MBK1zHJ140Nig6sm5cmy38q1A-rCk7bGYYP34PRz-53HjIm5CPf6UnYhXJZK18z4SxKT
TOY4ZdHVxaPvsS6JXh8EQd4N53lNwWAhr0E29IuKawCJB99imnOsYBbIP6mJAqSPurWdERFyp6ZJZjQvjxt0nl4wzYeXEy7ALjqcoB56cfTYTro8NMpAZWU9
kRSXQW6GMeWR0DrD9UOfc_vPl7TeIPKRKgVxesYNONEDbT8EBvhNsobvqRo2ec29s6xmQR1UQAYxsouySFRnm6qRK0y-vGssFiQqE9BOIpeOn_tTOq7zUFXh
VfgqCFwQG2vthkRkTfV-BtkJtnPriesCkKQqjYtsiAo0P0zB1tziONcrOmVBUzEkOuqtejk2VA7X1RaXFlRa6bPElAo2YAZPs60g8ZXr3-IhjuqdNrd58hQJ
zc9So59sen7voePW3l2yARy7jOtx2GZ_XoL9JEv-oZk3aDrt-5tgCwrTk0LwtdIgTvPGxWHLoET_UO2tNMcWO8QsIzBem4W4Ec6kIjHly1lGLThVrj_NFm
}

