sprite $rabbitmq [73x86/16z] {
xTFL0SK034BH66J_YP-xkxIS0UuNs6U929iz0xSToLv2s6rwW_lrDSRjdHNRojwYFn6gaOGKKaWXXHHosq3lY7j3s9IIlGFtXfge6G2z3wUKxuUUa0ejAQGG
YJdooP1jE9u9qRRYcL3PbZyVMld3a4B-ga7cCw4EMmj-_FqAAQHGs0wm7qJOa8bC0G
}

