sprite $router [51x51/8z] {
bPO7GYKm24GP1hZ_aNSJowGPpTFVUUa5Em6m0TYVwD6EXfFahu87iPGGVXKKFra_IWW9C_x3BzTcq__wfN3QIi3k81wDtQ6CYyEz7xGxxgkUbNO4JYoD2Mkm
gX9xTDP_eCY6VtxEtM5ziZIDPhFZN9tu_gnAHiSLOHPTeHggzibf3_Kbk-8gGiCbfm4P-jpXvsDpV338AlqEhefNXp9QI9e8AQDH-Mr4_ze4bwwGMPrkT7U5
W1-MHoIw8aCuBciOAKE05yLWpuezAC2hWanS5FZ1gEfE9Nrp7U39gDJYoU1oJD24oz32rpe-BPZoqJ3Ac1MeILNinhJYSZ-Pk2vAnNn-XWdEkvApqVkVYnFQ
-neXZXlVRNQm799LSdIAJWxdSmnr65Gvqn4Rwds6sZaveSW6UBafnzEQc8xqArJOy_toVeizEJBUR-JxbxyNYF37xE8zXtdFb0I3oiU2jlEUzVq3
}

