sprite $storage [65x28/8z] {
xPM7haCn24DjRFZ_FtuZGxmHhQRQzxHt8Uje1G2ero40rGq2A_0wKLJYXfIC6xm58TjPQIimeRHB8d28jI0ofU0N8MMEkCiIPyrb_8z52vmY5jH8inp48h9u
YhN0hYzotEqfK8vQVjzKFCLQ800S0D0KpDAg5S-n5ZGjQ5hGl5tm21v1PFfFcy6LgnkbxaQVkn6WHgUuvm4GUnvqN_wB-NeYtGkkX-hrMBzUBDUhxHC
}

