sprite $switch [51x51/16z] {
lTPLbaGX38JX50G9gNDw_xiTTu4QwV_vVjUHImigHRjuHbUAz46O4ZWcJOlptqY7JBXS9cIK0-Bn7EyQs9BETwNBX9mgoMORWlhSvbdqDrOXVXSCLkthzoIh
ye_LnTj6Vyft19FlYWrnKYNMKYQ6GV5PRYj1yOtTvaibj_LYRsfT7lkTgyg4d3WWV5jsg8HSBXCkY2IR-FWSC8r4-V8b0v-HvHy-vMOC5tmzNdPZ-3qfyVQ_
xpk2mVTjY2TLOYrbOXXKdkNBCRmVbRvaOkW24ReQ-S6snpEydkUH_eCjt6t5pYktnzy
}

