sprite $teamcity [69x66/16z] {
rTK7ikiW38LXgevIp_vt-xXt24OnTXXU_zAOzaVkV1DIBbAWvKECmNEAQ8EkuxD8IKlsymbywJ91SYMH7sY3LyRNHYE1foujeQXKiwEJt9jhA3ggAHiIvhR5
LYI_uQ5yqC2k8HE3u4sUZwIZGR8Kan5jO4ZLToOEhv470W_4hN7lt4Rqo-Nis02Szkz7y3EHQ2PvNdlyTaCMlRD9tF5caflhiP3wwowi565yik4eqc9qiKKK
dbQkZM74VGlUHW0Lnvw_gE8Rg-lhpockkB40FRT8eM5tUpMHIukujkATDWADRxiMWqXTW9M9x6UHeqWkY-TX1CgEFuh4kZYAP7QWuqWwZzXHmYXI3yxzB19t
eyWkSY-BE8vKxCHnX6uxF5464MKFEepSN15lpuUMNnb473jn725SPn3nx7WC8dLTHGuYWHk7GQGIxufq9pzC8ZLoxdp79Yn6m2ReQYIRIsSXOdU9OZKYVCbO
ZQWpEsGXOYu_mM94azch2n7JOC9In3vvn4RkANVIVHnHn5ssYzoSSUM0IOmZlZEE9Bvn9hB8HbRzEn71vddcSQyUt4dOo24Wy8HNJ8WyXyyIFmcAKvev0QV4
qLZOA-8vAHrL972UZ2irCIllAkPodnHKRIDnHKBhQ4siy34983bv_fz-
}

