sprite $zabbix [105x30/16z] {
tPO7ZkWW30M7Nkz_tQrF6CJlPTke9S7oOCSeuStm2MBh_vcAcsz29xwLABobQ8H5V6QjXc3xQ0h8kUb9VWaFAUSnNnWfblb4zQ5C4OCtKUTa1G5rYieYl2Rs
BFAh23K8wDgCrbIHsp3HS40q4Jx561qeNO2OKWe0wJMRLXfugN7MkWC7tL9767QNLqYLI5q5nYwQIS4EnYtIocglntMxDL679D5OFQucKlE6DUuM1OMkV1vt
YIR4KvGEaJKFrNo9ClZzPimCpKGhIRugQajaHNhebqWPt9X2srdfbwWZ-H8LS3PrDabgyIKQhnc4Na-09NBX2O2w-gmdVkmYnKj_YpHDLdj_ZQ_xEP978k7x
bEXCbo-HCgUZFB_Ul4G-Fn5N0G5IVYAWcAiYnhn5IPajhkivuno60buY6zQoYIG5mYsgm7cW22zu2KmqDKt1TWnkYImcllXFqK0Lh0KCTufq3ayH9b9qc8Fx
7DahjaOApSXlYVIWw869F3O85YWWNQshFnP5g8fikoWhOj5sCR14YkOS1WTn5pK8oe_RH0rm6sq6QFi05ertIia158bIIY_p3ds9ZduKY2Ogd9In3hLzPYf6
LGUF4siYJPkAfLb5FkputhmlqqW-ZDcqchEMPbuVztfyoeVprlSUV7hZdvElzr_NtuJAc_48
}

